version: "3.5"

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql